version: '3.7'


networks:
  map_reduce_network:
    name: map_reduce_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16


services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      map_reduce_network:
        ipv4_address: 172.16.0.2


  keycloak:
    container_name: keycloak_0
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: zooops
      JDBC_PARAMS: 'useSSL=false'
    ports:
      - 8080:8080
    expose:
      - 8080      
    depends_on:
      - mysql
    volumes:
     - ./keycloak_data:/opt/keycloak/data/import
    networks:
      map_reduce_network:
        ipv4_address: 172.16.0.3

  kc_initiator:
    container_name: kc_initiator
    build: .
    volumes:
      - ./keycloak_data:/app
    environment:
      KEYCLOAK_URL: http://172.16.0.3:8080
      KEYCLOAK_USERNAME: admin
      KEYCLOAK_PASSWORD: zooops
    depends_on:
      - keycloak
    networks:
      map_reduce_network:
        ipv4_address: 172.16.0.5

  ui_svc:
    container_name: ui_svc
    image: php:8.0-apache
    volumes:
      - ./ui_svc_data:/var/www/html
      - ./ui_svc_data/php.ini:/usr/local/etc/php/php.ini
      - /var/run/docker.sock:/var/run/docker.sock
    user: www-data
    networks:
      map_reduce_network:
        ipv4_address: 172.16.0.4
    ports:
      - 80:80

  zookeeper1:
    image: zookeeper
    container_name: zookeeper1
    restart: always
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    ports:
      - 2181:2181
    networks:
      map_reduce_network:
        ipv4_address: 172.16.0.11

  zookeeper2:
    image: zookeeper
    container_name: zookeeper2
    restart: always
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    ports:
      - 2182:2181
    networks:
      map_reduce_network:
        ipv4_address: 172.16.0.12

  zookeeper3:
    image: zookeeper
    container_name: zookeeper3
    restart: always
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    ports:
      - 2183:2181
    networks:
      map_reduce_network:
        ipv4_address: 172.16.0.13

