FROM openjdk:20
# Set the working directory
WORKDIR /app

# Copy the JAR file into the container
COPY worker.jar /app/worker.jar

WORKDIR /app
# Set the command to run the JAR file
CMD ["java", "-jar", "/app/worker.jar"]