version: '3.1'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      map_reduce_network:
        ipv4_address: 172.16.0.2

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: zooops
    ports:
      - 443:8080
    depends_on:
      - mysql
    networks:
      map_reduce_network:
        ipv4_address: 172.16.0.3

  ui_svc:
    container_name: ui_svc
    build:
      context: ./
      dockerfile: Dockerfile_ui_svc
    volumes:
      - ./ui_svc_data:/var/www/html
    networks:
      map_reduce_network:
        ipv4_address: 172.16.0.4
    ports:
      - 80:80

networks:
  map_reduce_network:
    ipam:
      config:
        - subnet: 172.16.0.0/16
