version: '3.1'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      map_reduce_network:
        ipv4_address: 172.16.0.3

  keycloak:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - 80:8080
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
    depends_on:
      - postgresql
    volumes:
      - ./keycloak:/opt/bitnami/keycloak/themes/mynewtheme
    networks:
      map_reduce_network:
        ipv4_address: 172.16.0.4

volumes:
  postgresql_data:
    driver: local

networks:
  map_reduce_network:
    ipam:
      config:
        - subnet: 172.16.0.0/16